server:
  port: 8080
  error:
    include-stacktrace: always

spring:
  application:
    name: ecom
  profiles:
    active: default
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  data:
    cassandra:
      schema-action: NONE

astra:
  api:
    application-token: ${ASTRA_DB_APPLICATION_TOKEN}
    database-endpoint: https://30cdc24e-7a13-4825-8e22-b561b6bb5b33-us-east1.apps.astra.datastax.com
    # not mandatory for data API
    database-id: 30cdc24e-7a13-4825-8e22-b561b6bb5b33
    database-region: us-east1
    cross-region-failback: false
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: default_keyspace
        request:
          timeout: 8s
          consistency: LOCAL_QUORUM
          page-size: 5000
      advanced:
        connection:
          init-query-timeout: 10s
          set-keyspace-timeout: 10s
        control-connection:
          timeout: 10s
